### ISSUE TITLE
QGnomePlatform causes a graphical issue in the menubar of mGBA

### ISSUE THREAD

**Issue by darkgallium** [MartinBriza/QGnomePlatform#22] opened 2017-02-04 18:36 UTC
Hi, 

I'm using a GBA emulator using Qt 5 called mGBA on Fedora 25,
QGnomePlatform, which is shipped by default since this release, causes this weird graphical artifact on mGBA 
![mgba_qt_issue](https://cloud.githubusercontent.com/assets/17528199/22619695/aab23e3c-eafa-11e6-849e-ac90d618ebd8.png)
When I remove QGnomePlatform, this bug disappears. 
According to one developer of mGBA (mgba-emu/mgba#514), the problem needs to be fixed upstream.

Do you think it is possible to fix it on your side ?

**Comment by MartinBriza** [comment] 2017-02-05 00:08
Huh, interesting. It's either QGnomePlatform or adwaita-qt, both of which are my projects. I'll see what I can do, thanks for reporting.

**Comment by MartinBriza** [comment] 2017-02-06 08:32
So yeah, it's adwaita-qt. I'll fix it there. 
Please also consider reporting this bug against the Breeze theme which is the project adwaita-qt forked from. The problem is present in there, too.

**Comment by MartinBriza** [comment] 2017-02-06 08:35
Moving to MartinBriza/adwaita-qt#59

**Closed by MartinBriza** 2017-02-06 08:35 UTC
